# -*- coding: utf-8 -*-
"""datapreprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SkHYn8aaaIndo_Suiyof1QM2HknRI_da
"""

import pandas as pd
df = pd.read_csv("email_dataset_full.csv")
df.head()

df.columns

!pip install nltk

import re
import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")

def remove_signature(text):
    if pd.isna(text):
        return ""
    patterns = [
        r"regards,.*",
        r"thanks,.*",
        r"best regards,.*",
        r"sincerely,.*",
        r"kind regards,.*"
    ]
    for p in patterns:
        text = re.sub(p, "", text, flags=re.IGNORECASE | re.DOTALL)

    return text

def normalize_text(text):
    text = text.lower()
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

stop_words = set(stopwords.words("english"))
def remove_stopwords(text):
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

def preprocess_email(text):
    text = remove_signature(text)
    text = normalize_text(text)
    text = remove_stopwords(text)
    return text

df["cleaned_email"] = df["text"].apply(preprocess_email)
df[["text", "cleaned_email"]].head()

def label_urgency(text):
    if any(word in text for word in ["urgent", "asap", "immediately", "critical"]):
        return "High"
    elif any(word in text for word in ["soon", "priority"]):
        return "Medium"
    else:
        return "Low"

df["urgency"] = df["cleaned_email"].apply(label_urgency)
df[["cleaned_email", "category", "urgency"]].head()

df.to_csv("email_dataset_preprocessed.csv", index=False)

