# -*- coding: utf-8 -*-
"""m2_svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xZ6MJL4jQnMxeuoggkZ7iJvR-fT2j2kC
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

email_dataset_preprocessed = pd.read_csv("clean_email.csv")

print(email_dataset_preprocessed.head())

X = email_dataset_preprocessed["clean_text"]
y = email_dataset_preprocessed["Category"]

vectorizer = TfidfVectorizer(stop_words="english")
X_tfidf = vectorizer.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,
    y,
    test_size=0.2,
    random_state=42
)

svm_model = LinearSVC()

svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("SVM Accuracy:", accuracy * 100, "%")

print(classification_report(y_test, y_pred))

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

# Convert text to vectors
vectorizer = TfidfVectorizer()
X_vec = vectorizer.fit_transform(emails)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_vec, urgency_labels, test_size=0.2)

# Train SVM
model = SVC(kernel='linear', probability=True)
model.fit(X_train, y_train)